apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: #{service}#-hpa
  namespace: #{namespace}#
  labels:
    app.bancolombia.com.co/env: '#{env}#'
    app.bancolombia.com.co/cost-center: '#{cost-center}#'
    app.bancolombia.com.co/application-code: '#{application-code}#'
    app.bancolombia.com.co/project-name: '#{project-name}#'
    app.bancolombia.com.co/pmo: '#{pmo}#'
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: #{service}#-deployment
  minReplicas: 1
  maxReplicas: 50
  targetCPUUtilizationPercentage: 30
status:
  currentReplicas: 1
  desiredReplicas: 3
